name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./lost/pom.xml
          mvn clean package -f ./lostservice/pom.xml
          mvn clean package -f ./phone/pom.xml

      - name: Docker Build and push for Lost
        uses: docker/build-push-action@v4
        with:
          context: ./lost
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lost:latest
            ghcr.io/${{ github.repository }}/lost:${{ github.ref_name }}
            
      - name: Docker Build and push for Lostservice
        uses: docker/build-push-action@v4
        with:
          context: ./lostservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lostservice:latest
            ghcr.io/${{ github.repository }}/lostservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Phone
        uses: docker/build-push-action@v4
        with:
          context: ./phone
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/phone:latest
            ghcr.io/${{ github.repository }}/phone:${{ github.ref_name }}
            
