---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost
  labels:
    app: lost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost
  template:
    metadata:
      labels:
        app: lost
    spec:
      containers:
        - name: lost
          image: username/lost:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostservice
  labels:
    app: lostservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostservice
  template:
    metadata:
      labels:
        app: lostservice
    spec:
      containers:
        - name: lostservice
          image: username/lostservice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone
  labels:
    app: phone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phone
  template:
    metadata:
      labels:
        app: phone
    spec:
      containers:
        - name: phone
          image: username/phone:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: lost
  labels:
    app: lost
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lost


---


apiVersion: v1
kind: Service
metadata:
  name: lostservice
  labels:
    app: lostservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lostservice


---


apiVersion: v1
kind: Service
metadata:
  name: phone
  labels:
    app: phone
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phone

